### ISSUE TITLE
libsodium fails to build with ESP-IDF v6.0 when it defaults to picolibc (IEC-526)

### ISSUE THREAD

**Issue by 5p4k** [espressif/idf-extra-components#731]
### Answers checklist.

- [x] I have read the component documentation [ESP-IDF Components](https://components.espressif.com) and the issue is not addressed there.
- [x] I am using target and esp-idf version as defined in component's idf_component.yml
- [x] I have searched the [issue tracker](https://github.com/espressif/idf-extra-components/issues?q=is%3Aissue) for a similar issue and not found any related issue.

### Which component are you using? If you choose Other, provide details in More Information.

libsodium

### ESP-IDF version.

v6.0

### Development Kit.

esp32s3, esp32 (I suspect any really)

### Used Component version.

1.0.21

### More Information.

libsodium does not compile with ESP-IDF v6.0 [which uses picolibc](https://developer.espressif.com/blog/2026/04/esp-idf-6-default-libc-picolibc/), it gives the following build errors:

```
/home/spak/.espressif/tools/xtensa-esp-elf/esp-15.2.0_20251204/xtensa-esp-elf/picolibc/include/errno.h:43:9: error: unknown type name '__errno_t'; did you mean '__ino_t'?
   43 | typedef __errno_t errno_t;
      |         ^~~~~~~~~
      |         __ino_t
In file included from /home/spak/dev/test/managed_components/espressif__libsodium/libsodium/src/libsodium/sodium/utils.c:10:
/home/spak/.espressif/tools/xtensa-esp-elf/esp-15.2.0_20251204/xtensa-esp-elf/picolibc/include/string.h:219:9: error: unknown type name '__rsize_t'; did you mean '__ssize_t'?
  219 | typedef __rsize_t rsize_t;
      |         ^~~~~~~~~
      |         __ssize_t
```

The problem goes away if libc is switched to newlib in menuconfig. For anybody looking for how to do so, search for "newlib" in menuconfig, or go to _Component config_ > _LibC_ > _LibC to build application with_.

I'm attaching a sample app that fails to build.

[app.tar.gz](https://github.com/user-attachments/files/26839354/app.tar.gz)

**Comment by Lapshin** [comment]
Related to https://github.com/espressif/idf-extra-components/pull/730

**Comment by mahavirj** [comment]
Fixed with https://github.com/espressif/idf-extra-components/pull/730
